name: Bug Report
description: File a bug report to help us improve.
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: What happens?
      description: A short, clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Please provide steps to reproduce the behavior, preferably a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

        Format the code and the output as [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) using triple backticks:
        ````
        ```
        CODE HERE
        ```
        ````
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Environment"
  - type: input
    attributes:
      label: "OS:"
      placeholder: e.g., Linux, macOS, etc.
      description: Please include operating system version and architecture (e.g., aarch64, x86_64, etc.).
    validations:
      required: true
  - type: input
    attributes:
      label: "pg_mooncake Version:"
      placeholder: e.g., commit hash
    validations:
      required: true
  - type: input
    attributes:
      label: "Postgres Version:"
      placeholder: e.g., 17.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Are you using pg_mooncake Docker, Neon, or the extension standalone?
      options:
        - pg_mooncake Docker Image
        - pg_mooncake on Neon
        - pg_mooncake extension standalone
    validations:
      required: true
