blank_issues_enabled: false
contact_links:
  - name: Mooncake Devs Slack
    url: https://join.slack.com/t/mooncakelabs/shared_invite/zt-2sepjh5hv-rb9jUtfYZ9bvbxTCUrsEEA
    about: Our Slack community is the best place to get quick help and feedback.
