name: Feature Request
description: Suggest an idea for this project.
labels:
  - feature
body:
  - type: textarea
    attributes:
      label: What feature are you requesting?
      description: A short, clear and concise description of the desired feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why are you requesting this feature?
      description: A short, clear and concise description of why this feature is important.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is your proposed implementation for this feature?
      description: A short, clear and concise description of how you'd implement this feature.
    validations:
      required: false
